### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by cannorin** [uedajapan/lainTTL_repository#1]
[クリエイティブ・コモンズ](https://creativecommons.jp/licenses/) などのライセンスで公開していただけないでしょうか。

詳しい解説: "open source である" という文面では利用者に明示的にライセンスを与えていないため licensing として機能せず、現状ではライセンスなし = all rights reserved と同じ状態になっています。

[open source という言葉にはきちんとした定義があり](https://opensource.jp/osd/osd-japanese.html)、~~lain30thのTTLまでという条件~~lainTTLの使用条件(lain30thまで、国内居住者限定、etc)は実はこれと両立しないという問題もあります。クリエイティブ・コモンズなどでライセンスしなくても単に README から open source という表現を外すだけで問題は無くなりますが、できればクリエイティブ・コモンズでライセンスしていただけるとクリエイターとしては大変嬉しいです。

よろしくお願いします。

**Comment by hsgw** [comment]
クリエイティブ・コモンズなど既存のライセンスで配布された場合、国内居住者限定や期間などそのライセンスにない部分が複雑になるのではないでしょうか？

もし、混乱を招くのであれば、上で書かれているように"open source"という表現を外して利用規約へのリンクだけにする方が手間もかからず利用者も使いやすいと考えます。
（個人的には今のままでも規約へのリンクがあり明確にライセンスされていると思います）

**Comment by cannorin** [comment]
README の文面が変更されてライセンス関係の問題が無くなったのを確認したので、この issue を close します。

@uedajapan 様、対応いただきありがとうございます。
